import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
const chrome = spawn("google-chrome",["--headless","--disable-gpu","--hide-scrollbars","--no-sandbox","--remote-debugging-port=9351","--window-size=390,844","about:blank"],{stdio:"ignore"});
await new Promise(r=>setTimeout(r,1200));
const list = await (await fetch("http://localhost:9351/json/list")).json();
const ws = new WebSocket(list.find(t=>t.type==="page").webSocketDebuggerUrl);
let id=0; const pend=new Map();
const send=(m,p={})=>new Promise(res=>{const i=++id;pend.set(i,res);ws.send(JSON.stringify({id:i,method:m,params:p}))});
ws.addEventListener("message",e=>{const m=JSON.parse(e.data); if(m.id&&pend.has(m.id)){pend.get(m.id)(m.result);pend.delete(m.id);}});
await new Promise(r=>ws.addEventListener("open",r));
await send("Page.enable");
await send("Emulation.setDeviceMetricsOverride",{width:390,height:844,deviceScaleFactor:2,mobile:true});
await send("Page.navigate",{url:"http://localhost:3000/about"});
await new Promise(r=>setTimeout(r,3500));
await send("Runtime.evaluate",{expression:`[...document.querySelectorAll('p')].find(p=>p.textContent.trim()==='Trusted By')?.scrollIntoView({block:'center'})`});
await new Promise(r=>setTimeout(r,1500));
const {data}=await send("Page.captureScreenshot",{format:"png"});
writeFileSync("mq-mobile2.png",Buffer.from(data,"base64"));
ws.close(); chrome.kill(); process.exit(0);
